# Generated by Django 5.0.1 on 2024-02-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reocord',
            new_name='Record',
        ),
    ]
