# Generated by Django 5.0.1 on 2024-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_alter_record_phone_alter_record_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
